# spring配置
spring:
  application:
    name: nacos
  profiles:
    active: dev

nacos:
  # nacos 配置中心
  config:
    username: nacos # nacos开启认证
    password: nacos
    namespace: 6f4499ec-ad2c-45d5-b345-a21822a07680  # nacos命名空间
    bootstrap:
      enable: true
    server-addr: 127.0.0.1:8848 # 主配置服务器地址
    data-id: ${spring.application.name} # 主配置 data-id
    group: spring # 主配置 分组ID
    type: yaml  # 主配置 配置文件类型
    auto-refresh: true  # 主配置 开启自动刷新
  # nacos 注册中心
  discovery:
    auto-register: true
    namespace: 6f4499ec-ad2c-45d5-b345-a21822a07680  # nacos命名空间
    server-addr: 127.0.0.1:8848 # 主配置服务器地址
    register:
      service-name: ${spring.application.name}  # 主配置 data-id
      group-name: spring  # 主配置 分组ID

debug: true
